/* eslint-disable */
export default [
    {
        fileName: 'src/components/image.html',
        current: "<!-- target:TPL_component_pure_white_image -->\n<div class=\"${.} ec-pl-image-wrapper\">\n    <!-- if: ${rcvUrl} -->\n    <a href=\"${rcvUrl}\" title2=\"图片链接\" class=\"c-blocka\">\n        <!-- /if -->\n\n        <!-- import:TPL_component_pure_white_image-content -->\n\n        <!-- if: ${rcvUrl} -->\n    </a>\n    <!-- /if -->\n</div>\n\n<!-- target:TPL_component_pure_white_image-content -->\n<div class=\"${.outer-ctn}\" style=\"<!-- if: ${imgWidth} -->width: ${imgWidth};<!-- /if --><!-- if: ${isCenter} --> margin: 0 auto;<!-- /if -->\">\n    <div class=\"ec-pl-img ${imgGap} <!-- if: ${needImgRatioClass} -->${imgRatioClass}<!-- /if --> ${.ctn}\" style=\"<!-- if: ${imgRatio} --> height: 0; padding-bottom: ${imgRatio}; <!-- /if -->\">\n        <img src=\"${imgUrl}\">\n        <!-- if: ${hasVideoIcon} -->\n        <i class=\"c-icon ${.icon}\" style=\"font-size: ${iconSize}; line-height: ${iconSize}\">&#xe654</i>\n        <!-- /if -->\n        <!-- if: ${imgText} -->\n        <div class=\"ec-pl-img-text ${.text}\">${imgText}</div>\n        <!-- /if -->\n    </div>\n</div>\n\n<div class=\"ec-pl-image-title ${.title}<!-- if: ${titleClass} --> ${titleClass}<!-- /if -->\" style=\"<!--if: ${titleMargin} -->margin:${titleMargin};<!-- /if -->\">\n    <!-- if: ${imgTitleMain} -->\n    <div\n        class=\"<!-- if: ${mainTitleGap} -->${mainTitleGap} <!-- /if -->${mainTitleFont} <!-- if: ${mainLineClamp} --> ${mainLineClamp}<!-- /if --> ${.title-main}\">\n        ${imgTitleMain}\n    </div>\n    <!-- /if -->\n    <!-- if: ${imgTitleSub} -->\n    <div class=\"<!-- if: ${subTitleGap} -->${subTitleGap} <!-- /if -->${subTitleFont}\n    <!-- if: ${subLineClamp} --> ${subLineClamp}<!-- /if --> ${.title-sub}\">\n        ${imgTitleSub}\n    </div>\n    <!-- /if -->\n</div>\n\n",
        last: "<!-- target:TPL_component_pure_white_image -->\n<div class=\"${.} ec-pl-image-wrapper\">\n    <!-- if: ${rcvUrl} -->\n    <a href=\"${rcvUrl}\" title2=\"图片地址链接\" class=\"c-blocka\">\n        <!-- /if -->\n\n        <!-- import:TPL_component_pure_white_image-content -->\n\n        <!-- if: ${rcvUrl} -->\n    </a>\n    <!-- /if -->\n</div>\n\n<!-- target:TPL_component_pure_white_image-content -->\n<div class=\"${.outer-ctn}\" style=\"<!-- if: ${imgWidth} -->width: ${imgWidth};<!-- /if --><!-- if: ${isCenter} --> margin: 0 auto;<!-- /if -->\">\n    <div class=\"ec-pl-img ${imgGap} <!-- if: ${needImgRatioClass} -->${imgRatioClass}<!-- /if --> ${.ctn}\" style=\"<!-- if: ${imgRatio} --> height: 0; padding-bottom: ${imgRatio}; <!-- /if -->\">\n        <img src=\"${imgUrl}\">\n        <!-- if: ${hasVideoIcon} -->\n        <i class=\"c-icon ${.icon}\" style=\"font-size: ${iconSize}; line-height: ${iconSize}\">&#xe654</i>\n        <!-- /if -->\n        <!-- if: ${imgText} -->\n        <div class=\"ec-pl-img-text ${.text}\">${imgText}</div>\n        <!-- /if -->\n    </div>\n</div>\n\n<div class=\"ec-pl-image-title ${.title}<!-- if: ${titleClass} --> ${titleClass}<!-- /if -->\" style=\"<!--if: ${titleMargin} -->margin:${titleMargin};<!-- /if -->\">\n    <!-- if: ${imgTitleMain} -->\n    <div\n        class=\"<!-- if: ${mainTitleGap} -->${mainTitleGap} <!-- /if -->${mainTitleFont} <!-- if: ${mainLineClamp} --> ${mainLineClamp}<!-- /if --> ${.title-main}\">\n        ${imgTitleMain}\n    </div>\n    <!-- /if -->\n    <!-- if: ${imgTitleSub} -->\n    <div class=\"<!-- if: ${subTitleGap} -->${subTitleGap} <!-- /if -->${subTitleFont}\n    <!-- if: ${subLineClamp} --> ${subLineClamp}<!-- /if --> ${.title-sub}\">\n        ${imgTitleSub}\n    </div>\n    <!-- /if -->\n</div>\n\n"
    },
    {
        fileName: "src/components/image.less",
        current: ".ec-image {\n    &-icon {\n        position: absolute;\n        left: 50%;\n        top: 50%;\n        color: #fff;\n        background-color: rgba(0, 0, 0, .3);\n        border-radius: 50%;\n        transform: translate(-50%, -50%);\n    }\n}\n.ec-pl-image-title-top {\n    position: absolute;\n    top: 0;\n    left: 0;\n    right: 0;\n    margin-left: 10px;\n    margin-right: 10px;\n    padding: 10px;\n}\n.ec-image {\n    &-icon {\n        position: absolute;\n        left: 50%;\n        top: 50%;\n        color: #fff;\n        background-color: rgba(0, 0, 0, .3);\n        border-radius: 50%;\n        transform: translate(-50%, -50%);\n    }\n}\n.ec-image {\n    &-icon {\n        position: absolute;\n        left: 50%;\n        top: 50%;\n        color: #fff;\n        background-color: rgba(0, 0, 0, .3);\n        border-radius: 50%;\n        transform: translate(-50%, -50%);\n    }\n}",
        last: ".ec-image {\n    &-icon {\n        position: absolute;\n        left: 50%;\n        top: 50%;\n        color: #fff;\n        background-color: rgba(0, 0, 0, .3);\n        border-radius: 50%;\n        transform: translate(-50%, -50%);\n    }\n}\n.ec-pl-image-title-top {\n    position: absolute;\n    top: 0;\n    left: 0;\n    right: 0;\n    margin: 10px;\n}\n.ec-image {\n    &-icon {\n        position: absolute;\n        left: 50%;\n        top: 50%;\n        color: #fff;\n        background-color: rgba(0, 0, 0, .3);\n        border-radius: 20%;\n        border: 2px;\n        transform: translate(-50%, -50%);\n    }\n}\n.ec-image {\n    &-icon {\n        position: absolute;\n        left: 50%;\n        top: 50%;\n        color: #fff;\n        background-color: rgba(0, 0, 0, .3);\n        border-radius: 50%;\n        transform: translate(-50%, -50%);\n    }\n}"
    },
    {
        fileName: "src/components/ImageDelete.less",
        current: "",
        last: ".ec-image {\n    &-icon {\n        position: absolute;\n        left: 50%;\n        top: 50%;\n        color: #fff;\n        background-color: rgba(0, 0, 0, .3);\n        border-radius: 50%;\n        transform: translate(-50%, -50%);\n    }\n}\n.ec-pl-image-title-top {\n    position: absolute;\n    top: 0;\n    left: 0;\n    right: 0;\n    margin: 10px;\n}\n"
    },
    {
        fileName: "src/components/TestAdd.less",
        last: "",
        current: ".ec-image {\n    &-icon {\n        position: absolute;\n        left: 50%;\n        top: 50%;\n        color: #fff;\n        background-color: rgba(0, 0, 0, .3);\n        border-radius: 50%;\n        transform: translate(-50%, -50%);\n    }\n}\n.ec-pl-image-title-top {\n    position: absolute;\n    top: 0;\n    left: 0;\n    right: 0;\n    margin: 10px;\n}\n"
    }
];